In [2]:
#1. Import the numpy package under the name np
import numpy as np

In [7]:
#2. Print the numpy version and the configuration
import numpy
print(numpy.__version__)
print(numpy.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/prade/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/prade/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/prade/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/prade/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/prade/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/prade/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/prade/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/prade/anaconda3\\Library\\include']
None


In [8]:
#3. Create a null vector of size 10
import numpy
x = numpy.zeros(10)
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
#4. How to find the memory size of any array
import numpy 
n = numpy.zeros((3,3))
print("%d bytes" % (n.size * n.itemsize))
print(n)

72 bytes
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
#5. How to get the documentation of the numpy add function from the command line?
#solution: %run `python -c "import numpy;numpy.info(numpy.add)"`

In [7]:
#6. Create  a null vector of size 10 but the fifth value which is 1
import numpy
a = numpy.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
#7. Create a vector with values ranging from 10 to 49
import numpy
a = numpy.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
#8. Reverse a vector (first element becomes last)
import numpy
a = np.arange(10)
a = a[::-1]
print(a)

[9 8 7 6 5 4 3 2 1 0]


In [17]:
#9. Create a 3x3 matrix with values ranging from 0 to 8 
import numpy
a = numpy.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
#10.Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy
a = numpy.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4], dtype=int64),)


In [19]:
#11.Create a 3x3 identity matrix
import numpy
a = numpy.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#12. Create a 3x3x3 array with random values
import numpy
a = numpy.random.random((3,3,3))
print(a)

[[[0.92702662 0.50619203 0.04399681]
  [0.09390466 0.83074852 0.1146198 ]
  [0.82893372 0.55693697 0.23027447]]

 [[0.04002441 0.20687537 0.30433557]
  [0.96407858 0.29333474 0.91645741]
  [0.811312   0.65169478 0.72702314]]

 [[0.16345553 0.42446902 0.13817046]
  [0.33956831 0.7379742  0.89920483]
  [0.27407263 0.09911833 0.6196698 ]]]


In [41]:
#13. Create a 10x10 array with random values and find the minimum and maximum values.
import numpy
P = numpy.random.random((10,10))
Pmin, Pmax = P.min(), P.max()
print(Pmin, Pmax)

0.003964712113317392 0.9999211721888317


In [40]:
#14. Create a random vector of size 30 and find the mean value
import numpy
a = numpy.random.random(30)
p = a.mean()
print(p)

0.43666336170974385


In [3]:
#15.Create a 2d array with 1 on the border and 0 inside
import numpy
a = numpy.ones((5,5))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [46]:
#34.How to get all the dates corresponding to the month of July 2016
import numpy
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [59]:
#42. Consider two random array A and B, check if they are equal
import numpy
A = numpy.random.randint(1,2,6)
B = numpy.random.randint(1,2,6)
a = numpy.allclose(A,B)
print(a)
b = numpy.array_equal(A,B)
print(b)

True
True


In [1]:
#16. How to add a border (filled with 0's) around an existing array?
import numpy
a = numpy.ones((5,5))
a = numpy.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [6]:
#17. What is the result of the following expression?
import numpy
print(0 * numpy.nan)
print(numpy.nan == numpy.nan)
print(numpy.inf > numpy.nan)
print(numpy.nan - numpy.nan)
print(numpy.nan in set([numpy.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [8]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
import numpy
a = numpy.diag(1+numpy.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [9]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern
import numpy
a = numpy.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [11]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
import numpy
print(numpy.unravel_index(100,(6,7,8)))

(1, 5, 4)
